### ISSUE TITLE
Clarification on config file

### ISSUE THREAD

**Issue by danthi123** [ozangulle/plauna#2]
No matter how I change it, I can't seem to get a valid config and would appreciate some clarification on the values and formatting.

So the sample in the ReadMe is:
{:data-folder "/home/myhome/example-directory" ; the location for the db, training files and models
 :server {:port 80}
 :email {
         :clients [{:host "imap.example.com" :user "me@example.com" :secret "mysecret" :folder "Inbox"}]
}}

Is the :data-folder path supposed to be host path or the container path?
Trying to install in Unraid, the container path is listed as /data, which I map to /mnt/user/appdata/plauna/data on my host.
Note: This folder remains empty when attempting to start the container.

For :port, same question. Is that the internal container port, which defaults to 8085 on Unraid?
I have it mapped to 8085 on my host as well and have tried both docker bridge and host networking.

Regarding the :email section, the sample lists an IMAP host but how does it determine the port and encryption?
I'm assuming :secret is the IMAP password?
How do I enter SMTP credentials into the config?

Lastly, when I change my actual config file, the container logs seem to show it sticking to past configs randomly (which usually mention connection errors with the entered IMAP settings).

**Comment by ozangulle** [comment]
I'll gladly try to help you but I must warn you that I don't know anything about Unraid and the app on unraid.net is not created by me but by another community member. I don't know how that app (or Unraid) uses the docker image.

> Is the :data-folder path supposed to be host path or the container path?

It's the path on the container. As I mentioned in another issue, the way I do it is to create a docker volume, place the config file in the docker volume on the host and than mount that volume at /opt/plauna on the container. It looks like this:

```json
"Mounts": [
        {
            "Destination": "/opt/plauna",
            "Driver": "local",
            "Mode": "z",
            "Name": "plauna-storage",
            "Propagation": "",
            "RW": true,
            "Source": "/var/lib/docker/volumes/plauna-storage/_data",
            "Type": "volume"
        }
    ],
```

> For :port, same question. Is that the internal container port, which defaults to 8085 on Unraid?
I have it mapped to 8085 on my host as well and have tried both docker bridge and host networking.

It's the port that the server listens to in the container. If you use host networking, your OS may not like you using port 80. It's set to 8080 in my config and I expose it using traeffik. Here's what my docker-compose config looks like:

```yaml
version: "3"

services:
  plauna:
    container_name: plauna
    image: ozangulle/plauna:dev
    networks:
      - "traefik"
    environment:
      - 'PLAUNA_ARGS=--config-file=/opt/plauna/plauna.edn'
    volumes:
      - 'plauna-storage:/opt/plauna/'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plauna.rule=Host(`--redacted--`)"
      - "traefik.http.routers.plauna.tls=true"
      - "traefik.http.routers.plauna.entrypoints=https"
      - "traefik.http.services.plauna-service.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true

volumes:
  plauna-storage:
    external: true
```

> Regarding the :email section, the sample lists an IMAP host but how does it determine the port and encryption?
I'm assuming :secret is the IMAP password?
How do I enter SMTP credentials into the config?

SSL is always turned on and the underlying library (that's jakarta mail) should use the standard port for IMAPS (which is 993 if I'm not mistaken). I'm working on a new feature that allows the users to choose the encryption type (SSL, STARTTLS, and plaintext) and to specify the port. ":secret" is the IMAP password. Plauna does not send e-mails so there is no way to enter your SMTP credentials.

> Lastly, when I change my actual config file, the container logs seem to show it sticking to past configs randomly (which usually mention connection errors with the entered IMAP settings).

I don't quite understand this. You change the config file that you mount but it still uses the previous version of the config file? Is this after a container restart?
